<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UniversitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('universities')->truncate();

        $universities = [
            ['name' => 'University of Dhaka', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Rajshahi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Agricultural University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Chittagong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jahangirnagar University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islamic University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shahjalal University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khulna University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangabandhu Sheikh Mujib Medical University ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hajee Mohammad Danesh Science & Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mawlana Bhashani Science and Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Patuakhali Science and Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sher-e-Bangla Agricultural University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dhaka University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rajshahi University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chittagong University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khulna University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jagannath University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jatiya Kabi Kazi Nazrul Islam University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chittagong Veterinary and Animal Sciences University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sylhet Agricultural University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Comilla University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Noakhali Science and Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jessore University of Science & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pabna University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh University of Professionals', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Begum Rokeya University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh University of Textiles', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Barisal', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islamic Arabic University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Maritime University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rangamati Science and Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dhaka International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ahsanullah University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'BRAC University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'East West University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'North South University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'American International University-Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Independent University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh University of Business and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gono Bishwabidyalay', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hamdard University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'International Islamic University, Chittagong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chittagong Independent University (CIU)', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Science & Technology Chittagong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Begum Gulchemonara Trust University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'East Delta University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Army University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Army International University of Science & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Britannia University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Feni University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Army University of Engineering & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Premier University, Chittagong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Exim Bank Agricultural University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Southern University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Port City International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Coxs Bazar International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Notre Dame University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asian University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asa University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Atish Dipankar University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Islami University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Central Women\'s University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'City University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Daffodil International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Eastern University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Green University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'IBAIS University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sonargaon University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'International University of Business Agriculture and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Manarat International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Millennium University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Northern University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'North Western University, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'People\'s University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Presidency University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pundra University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Prime University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'European University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Primeasia University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Queens University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rajshahi Science & Technology University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Royal University of Dhaka', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shanto-Mariam University of Creative Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Southeast University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Stamford University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'State University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'United International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Asia Pacific (Bangladesh)', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Development Alternative', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Information Technology and Sciences', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Liberal Arts Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fareast International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of South Asia, Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Uttara University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Victoria University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Varendra University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'World University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Leading University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Metropolitan University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'North East University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sylhet International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khwaja Yunus Ali University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Global University Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'University of Creative Technology Chittagong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Z H Sikder University of Science & Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Central University of Science and Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Canadian University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'First Capital University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ishaka International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Northern University of Business & Technology, Khulna', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'North Bengal International University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ranada Prasad Shaha University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islamic University of Technology', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Asian University for Women', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bangladesh Open University', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'National University of Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Islamic Arabic University', 'created_at' => now(), 'updated_at' => now()],
        ];

        \DB::table('universities')->insert($universities);
    }
}
