<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UniversitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('universities')->truncate();

        $universities = [
            ['name' => 'University of Dhaka'],
            ['name' => 'University of Rajshahi'],
            ['name' => 'Bangladesh Agricultural University'],
            ['name' => 'Bangladesh University of Engineering & Technology'],
            ['name' => 'University of Chittagong'],
            ['name' => 'Jahangirnagar University'],
            ['name' => 'Islamic University, Bangladesh'],
            ['name' => 'Shahjalal University of Science and Technology'],
            ['name' => 'Khulna University'],
            ['name' => 'Bangabandhu Sheikh Mujib Medical University '],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University'],
            ['name' => 'Hajee Mohammad Danesh Science & Technology University'],
            ['name' => 'Mawlana Bhashani Science and Technology University'],
            ['name' => 'Patuakhali Science and Technology University'],
            ['name' => 'Sher-e-Bangla Agricultural University'],
            ['name' => 'Dhaka University of Engineering & Technology'],
            ['name' => 'Rajshahi University of Engineering & Technology'],
            ['name' => 'Chittagong University of Engineering & Technology'],
            ['name' => 'Khulna University of Engineering & Technology'],
            ['name' => 'Jagannath University'],
            ['name' => 'Jatiya Kabi Kazi Nazrul Islam University'],
            ['name' => 'Chittagong Veterinary and Animal Sciences University'],
            ['name' => 'Sylhet Agricultural University'],
            ['name' => 'Comilla University'],
            ['name' => 'Noakhali Science and Technology University'],
            ['name' => 'Jessore University of Science & Technology'],
            ['name' => 'Pabna University of Science and Technology'],
            ['name' => 'Bangladesh University of Professionals'],
            ['name' => 'Begum Rokeya University'],
            ['name' => 'Bangladesh University of Textiles'],
            ['name' => 'University of Barisal'],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University'],
            ['name' => 'Islamic Arabic University'],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Maritime University'],
            ['name' => 'Rangamati Science and Technology University'],
            ['name' => 'Dhaka International University'],
            ['name' => 'Ahsanullah University of Science and Technology'],
            ['name' => 'BRAC University'],
            ['name' => 'East West University'],
            ['name' => 'North South University'],
            ['name' => 'American International University-Bangladesh'],
            ['name' => 'Independent University, Bangladesh'],
            ['name' => 'Bangladesh University of Business and Technology'],
            ['name' => 'Gono Bishwabidyalay'],
            ['name' => 'Hamdard University Bangladesh'],
            ['name' => 'International Islamic University, Chittagong'],
            ['name' => 'Chittagong Independent University (CIU)'],
            ['name' => 'University of Science & Technology Chittagong'],
            ['name' => 'Begum Gulchemonara Trust University'],
            ['name' => 'East Delta University'],
            ['name' => 'Bangladesh Army University of Science and Technology'],
            ['name' => 'Bangladesh Army International University of Science & Technology'],
            ['name' => 'Britannia University'],
            ['name' => 'Feni University'],
            ['name' => 'Bangladesh Army University of Engineering & Technology'],
            ['name' => 'Premier University, Chittagong'],
            ['name' => 'Exim Bank Agricultural University Bangladesh'],
            ['name' => 'Southern University, Bangladesh'],
            ['name' => 'Port City International University'],
            ['name' => 'Coxs Bazar International University'],
            ['name' => 'Notre Dame University Bangladesh'],
            ['name' => 'Asian University of Bangladesh'],
            ['name' => 'Asa University Bangladesh'],
            ['name' => 'Atish Dipankar University of Science and Technology'],
            ['name' => 'Bangladesh Islami University'],
            ['name' => 'Bangladesh University'],
            ['name' => 'Central Women\'s University'],
            ['name' => 'City University, Bangladesh'],
            ['name' => 'Daffodil International University'],
            ['name' => 'Eastern University, Bangladesh'],
            ['name' => 'Green University of Bangladesh'],
            ['name' => 'IBAIS University'],
            ['name' => 'Sonargaon University'],
            ['name' => 'International University of Business Agriculture and Technology'],
            ['name' => 'Manarat International University'],
            ['name' => 'Millennium University'],
            ['name' => 'Northern University, Bangladesh'],
            ['name' => 'North Western University, Bangladesh'],
            ['name' => 'People\'s University of Bangladesh'],
            ['name' => 'Presidency University'],
            ['name' => 'Pundra University of Science and Technology'],
            ['name' => 'Prime University'],
            ['name' => 'European University of Bangladesh'],
            ['name' => 'Primeasia University'],
            ['name' => 'Queens University'],
            ['name' => 'Rajshahi Science & Technology University'],
            ['name' => 'Royal University of Dhaka'],
            ['name' => 'Shanto-Mariam University of Creative Technology'],
            ['name' => 'Southeast University'],
            ['name' => 'Stamford University Bangladesh'],
            ['name' => 'State University of Bangladesh'],
            ['name' => 'United International University'],
            ['name' => 'University of Asia Pacific (Bangladesh)'],
            ['name' => 'University of Development Alternative'],
            ['name' => 'University of Information Technology and Sciences'],
            ['name' => 'University of Liberal Arts Bangladesh'],
            ['name' => 'Fareast International University'],
            ['name' => 'University of South Asia, Bangladesh'],
            ['name' => 'Uttara University'],
            ['name' => 'Victoria University of Bangladesh'],
            ['name' => 'Varendra University'],
            ['name' => 'World University of Bangladesh'],
            ['name' => 'Leading University'],
            ['name' => 'Metropolitan University'],
            ['name' => 'North East University Bangladesh'],
            ['name' => 'Sylhet International University'],
            ['name' => 'Khwaja Yunus Ali University'],
            ['name' => 'Global University Bangladesh'],
            ['name' => 'University of Creative Technology Chittagong'],
            ['name' => 'Z H Sikder University of Science & Technology'],
            ['name' => 'Central University of Science and Technology'],
            ['name' => 'Canadian University of Bangladesh'],
            ['name' => 'First Capital University of Bangladesh'],
            ['name' => 'Ishaka International University'],
            ['name' => 'Northern University of Business & Technology, Khulna'],
            ['name' => 'North Bengal International University'],
            ['name' => 'Ranada Prasad Shaha University'],
            ['name' => 'Islamic University of Technology'],
            ['name' => 'Asian University for Women'],
            ['name' => 'Bangladesh Open University'],
            ['name' => 'National University of Bangladesh'],
            ['name' => 'Islamic Arabic University'],
        ];

        \DB::table('universities')->insert($universities);
    }
}
